In [1]:
import pandas as pd 

Nn=pd.read_csv("df_N.csv") 
Nn

,type,rating_category,Duration_Category,movie_age,content_age_years,country_category,Directors,Title_Words
0,Movie,Adult,Medium,5,3,United States,Other Directors,1-5 Words
1,TV Show,Adult,Series(X Seasons),4,3,Other Countries,Other Directors,1-5 Words
2,TV Show,Adult,Series(X Seasons),4,3,Other Countries,Other Directors,1-5 Words
3,TV Show,Adult,Series(X Seasons),4,3,Other Countries,Other Directors,1-5 Words
4,TV Show,Adult,Series(X Seasons),4,3,India,Other Directors,1-5 Words
...,...,...,...,...,...,...,...,...
8799,Movie,Adult,Epic,18,5,United States,Other Directors,1-5 Words
8800,TV Show,Family-friendly,Series(X Seasons),7,5,Other Countries,Other Directors,1-5 Words
8801,Movie,Adult,Medium,16,5,United States,Other Directors,1-5 Words
8802,Movie,Teen/Young Adult,Medium,19,5,United States,Other Directors,1-5 Words
8803,Movie,Teen/Young Adult,Long,10,5,India,Other Directors,1-5 Words

In [3]:
Nn["rating_category"].value_counts()

rating_category
Adult               4503
Teen/Young Adult    2453
Family-friendly     1765
Uncategorized         83
Name: count, dtype: int64

In [5]:
Nn = Nn[Nn['rating_category'] != 'Uncategorized'] 
Nn.head()

,type,rating_category,Duration_Category,movie_age,content_age_years,country_category,Directors,Title_Words
0,Movie,Adult,Medium,5,3,United States,Other Directors,1-5 Words
1,TV Show,Adult,Series(X Seasons),4,3,Other Countries,Other Directors,1-5 Words
2,TV Show,Adult,Series(X Seasons),4,3,Other Countries,Other Directors,1-5 Words
3,TV Show,Adult,Series(X Seasons),4,3,Other Countries,Other Directors,1-5 Words
4,TV Show,Adult,Series(X Seasons),4,3,India,Other Directors,1-5 Words

In [9]:
Nn = Nn.reset_index(drop=True) 
Nn

,type,rating_category,Duration_Category,movie_age,content_age_years,country_category,Directors,Title_Words
0,Movie,Adult,Medium,5,3,United States,Other Directors,1-5 Words
1,TV Show,Adult,Series(X Seasons),4,3,Other Countries,Other Directors,1-5 Words
2,TV Show,Adult,Series(X Seasons),4,3,Other Countries,Other Directors,1-5 Words
3,TV Show,Adult,Series(X Seasons),4,3,Other Countries,Other Directors,1-5 Words
4,TV Show,Adult,Series(X Seasons),4,3,India,Other Directors,1-5 Words
...,...,...,...,...,...,...,...,...
8716,Movie,Adult,Epic,18,5,United States,Other Directors,1-5 Words
8717,TV Show,Family-friendly,Series(X Seasons),7,5,Other Countries,Other Directors,1-5 Words
8718,Movie,Adult,Medium,16,5,United States,Other Directors,1-5 Words
8719,Movie,Teen/Young Adult,Medium,19,5,United States,Other Directors,1-5 Words
8720,Movie,Teen/Young Adult,Long,10,5,India,Other Directors,1-5 Words

In [11]:
Nn.to_csv("Nn.csv",index=False)

In [1]:
import pandas as pd 
Nd=pd.read_csv("Nn.csv") 
Nd

,type,rating_category,Duration_Category,movie_age,content_age_years,country_category,Directors,Title_Words
0,Movie,Adult,Medium,5,3,United States,Other Directors,1-5 Words
1,TV Show,Adult,Series(X Seasons),4,3,Other Countries,Other Directors,1-5 Words
2,TV Show,Adult,Series(X Seasons),4,3,Other Countries,Other Directors,1-5 Words
3,TV Show,Adult,Series(X Seasons),4,3,Other Countries,Other Directors,1-5 Words
4,TV Show,Adult,Series(X Seasons),4,3,India,Other Directors,1-5 Words
...,...,...,...,...,...,...,...,...
8716,Movie,Adult,Epic,18,5,United States,Other Directors,1-5 Words
8717,TV Show,Family-friendly,Series(X Seasons),7,5,Other Countries,Other Directors,1-5 Words
8718,Movie,Adult,Medium,16,5,United States,Other Directors,1-5 Words
8719,Movie,Teen/Young Adult,Medium,19,5,United States,Other Directors,1-5 Words
8720,Movie,Teen/Young Adult,Long,10,5,India,Other Directors,1-5 Words

In [3]:
def netflix_added_year(A):
    if A<=5:
        return "New Releases (0-5 years)" 
    elif A<=10:
        return "Moderately Aged (6-10 years)"
    else:
        return "Older Content (11-17 years)"
    
Nd["Content Age"]= Nd["content_age_years"].apply(netflix_added_year) 
Nd.head()

,type,rating_category,Duration_Category,movie_age,content_age_years,country_category,Directors,Title_Words,Content Age
0,Movie,Adult,Medium,5,3,United States,Other Directors,1-5 Words,New Releases (0-5 years)
1,TV Show,Adult,Series(X Seasons),4,3,Other Countries,Other Directors,1-5 Words,New Releases (0-5 years)
2,TV Show,Adult,Series(X Seasons),4,3,Other Countries,Other Directors,1-5 Words,New Releases (0-5 years)
3,TV Show,Adult,Series(X Seasons),4,3,Other Countries,Other Directors,1-5 Words,New Releases (0-5 years)
4,TV Show,Adult,Series(X Seasons),4,3,India,Other Directors,1-5 Words,New Releases (0-5 years)

In [5]:
Nd.drop(columns=["content_age_years"],inplace=True)

In [7]:
Nd.head()

,type,rating_category,Duration_Category,movie_age,country_category,Directors,Title_Words,Content Age
0,Movie,Adult,Medium,5,United States,Other Directors,1-5 Words,New Releases (0-5 years)
1,TV Show,Adult,Series(X Seasons),4,Other Countries,Other Directors,1-5 Words,New Releases (0-5 years)
2,TV Show,Adult,Series(X Seasons),4,Other Countries,Other Directors,1-5 Words,New Releases (0-5 years)
3,TV Show,Adult,Series(X Seasons),4,Other Countries,Other Directors,1-5 Words,New Releases (0-5 years)
4,TV Show,Adult,Series(X Seasons),4,India,Other Directors,1-5 Words,New Releases (0-5 years)

In [9]:
Nd.to_csv("Nd.csv",index=False)

In [23]:
Nd["type"].unique()

array(['Movie', 'TV Show'], dtype=object)

In [25]:
Nd["Duration_Category"].unique()

array(['Medium', 'Series(X Seasons)', 'Long', 'Very Long', 'Epic',
       'Very Short', 'Short'], dtype=object)

In [27]:
Nd["country_category"].unique()

array(['United States', 'Other Countries', 'India', 'United Kingdom',
       'Japan', 'South Korea'], dtype=object)

In [29]:
Nd["rating_category"].unique()

array(['Adult', 'Teen/Young Adult', 'Family-friendly'], dtype=object)

In [31]:
Nd["Directors"].unique()

array(['Other Directors', 'Rajiv Chilaka', 'Suhas Kadav',
       'Cathy Garcia-Molina', 'Marcus Raboy', 'Jay Karas'], dtype=object)

In [33]:
Nd["Title_Words"].unique()

array(['1-5 Words', '6-10 Words', '11-15 Words', 'More than 15 words'],
      dtype=object)

In [35]:
Nd["Content Age"].unique()

array(['New Releases (0-5 years)', 'Moderately Aged (6-10 years)',
       'Older Content (11-17 years)'], dtype=object)

In [11]:
import pandas as pd 

NT=pd.read_csv("Nd.csv") 
NT.head()

,type,rating_category,Duration_Category,movie_age,country_category,Directors,Title_Words,Content Age
0,Movie,Adult,Medium,5,United States,Other Directors,1-5 Words,New Releases (0-5 years)
1,TV Show,Adult,Series(X Seasons),4,Other Countries,Other Directors,1-5 Words,New Releases (0-5 years)
2,TV Show,Adult,Series(X Seasons),4,Other Countries,Other Directors,1-5 Words,New Releases (0-5 years)
3,TV Show,Adult,Series(X Seasons),4,Other Countries,Other Directors,1-5 Words,New Releases (0-5 years)
4,TV Show,Adult,Series(X Seasons),4,India,Other Directors,1-5 Words,New Releases (0-5 years)

In [13]:
from sklearn.preprocessing import LabelEncoder 

Categorical_columns=["type","rating_category","Duration_Category","country_category","Directors","Title_Words","Content Age"] 

le=LabelEncoder() 

for col in Categorical_columns:
    NT[col]=le.fit_transform(NT[col]) 

NT.head()

,type,rating_category,Duration_Category,movie_age,country_category,Directors,Title_Words,Content Age
0,0,0,2,5,5,3,0,1
1,1,0,3,4,2,3,0,1
2,1,0,3,4,2,3,0,1
3,1,0,3,4,2,3,0,1
4,1,0,3,4,0,3,0,1

In [15]:
from sklearn.preprocessing import StandardScaler 

scaler=StandardScaler() 

NT["movie_age"]=scaler.fit_transform(NT["movie_age"].values.reshape(-1, 1)) 

NT.head()

,type,rating_category,Duration_Category,movie_age,country_category,Directors,Title_Words,Content Age
0,0,0,2,-0.658003,5,3,0,1
1,1,0,3,-0.771753,2,3,0,1
2,1,0,3,-0.771753,2,3,0,1
3,1,0,3,-0.771753,2,3,0,1
4,1,0,3,-0.771753,0,3,0,1

In [19]:
import pandas as pd 

cols=[col for col in NT.columns if col!="rating_category"]
cols.append("rating_category") 

NT=NT[cols] 
NT.head()

,type,Duration_Category,movie_age,country_category,Directors,Title_Words,Content Age,rating_category
0,0,2,-0.658003,5,3,0,1,0
1,1,3,-0.771753,2,3,0,1,0
2,1,3,-0.771753,2,3,0,1,0
3,1,3,-0.771753,2,3,0,1,0
4,1,3,-0.771753,0,3,0,1,0

In [21]:
NT["rating_category"].value_counts()

rating_category
0    4503
2    2453
1    1765
Name: count, dtype: int64

In [ ]:
                                       KNN CLASSIFICATION

In [49]:
                                #TRIAL AND ERROR METHOD TO FIND BEST N_NEIGHBORS 

from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score 

X=NT.drop(columns=["rating_category"]) 
y=NT["rating_category"]  

X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42) 

accuracies=[] 

k_values=range(1,16)

for k in k_values:
    model=KNeighborsClassifier(n_neighbors=k) 
    model.fit(X_train,y_train) 
    y_pred=model.predict(X_test) 
    accuracy=accuracy_score(y_test,y_pred) 
    accuracies.append(accuracy) 

best_k= k_values[accuracies.index(max(accuracies))] 
print(f"The best k value is: {best_k}")
print(f"Best Accuracy: {max(accuracies):.4f}")

The best k value is: 10
Best Accuracy: 0.5645

In [51]:
                                #KNN CLASSIFICATION 

from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix 

X=NT.drop(columns=["rating_category"]) 
y=NT["rating_category"]  


X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

model_d = KNeighborsClassifier(n_neighbors=10)

model_d.fit(X_train, y_train)

y_pred = model_d.predict(X_test)


print(classification_report(y_test, y_pred,zero_division=0))
print(confusion_matrix(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.59      0.82      0.68      1350
           1       0.39      0.24      0.30       545
           2       0.48      0.27      0.35       722

    accuracy                           0.55      2617
   macro avg       0.49      0.44      0.44      2617
weighted avg       0.52      0.55      0.51      2617

[[1101  128  121]
 [ 325  131   89]
 [ 447   79  196]]

In [53]:
                              #HYPERPARAMETER TUNING USING GRIDSEARCHCV 

from sklearn.model_selection import GridSearchCV 
from sklearn.metrics import classification_report 

param_grid = {
    'n_neighbors': [3, 5, 7, 9, 11, 13],        
    'weights': ['uniform', 'distance'],          
    'metric': ['euclidean', 'manhattan', 'minkowski'], 
    'algorithm': ['auto', 'ball_tree', 'kd_tree', 'brute'],  
}

grid_search = GridSearchCV(estimator=model_d, param_grid=param_grid, cv=5, scoring='accuracy', n_jobs=-1)

grid_search.fit(X_train, y_train)

print("Best Hyperparameters:", grid_search.best_params_)

best_knn = grid_search.best_estimator_
y_pred = best_knn.predict(X_test)

print(classification_report(y_test, y_pred,zero_division=0))

Best Hyperparameters: {'algorithm': 'auto', 'metric': 'manhattan', 'n_neighbors': 11, 'weights': 'uniform'}
              precision    recall  f1-score   support

           0       0.60      0.80      0.69      1350
           1       0.43      0.26      0.32       545
           2       0.46      0.31      0.37       722

    accuracy                           0.55      2617
   macro avg       0.50      0.46      0.46      2617
weighted avg       0.53      0.55      0.52      2617

In [ ]:
                                          DECISION TREE

In [55]:
                                     #TRIAL AND ERROR METHOD TO FIND BEST MAX_DEPTH


from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report  

X=NT.drop(columns=["rating_category"]) 
y=NT["rating_category"]  

X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42) 

max_depth_values = [5, 10, 15, 20]
min_samples_split_values = [2, 5, 10]
min_samples_leaf_values = [1, 2, 5]
criterion_values = ['gini', 'entropy'] 

best_accuracy=0
best_params={} 

for max_depth in max_depth_values:
    for min_samples_split in min_samples_split_values:
        for min_samples_leaf in min_samples_leaf_values:
            for criterion in criterion_values:

                clf=DecisionTreeClassifier(max_depth=max_depth,
                                           min_samples_split=min_samples_split,
                                           min_samples_leaf=min_samples_leaf,
                                           criterion=criterion,
                                           random_state=42) 
                clf.fit(X_train,y_train) 

                y_pred=clf.predict(X_test) 

                accuracy = accuracy_score(y_test, y_pred)
                if accuracy > best_accuracy:
                    best_accuracy = accuracy
                    best_params = {
                        'max_depth': max_depth,
                        'min_samples_split': min_samples_split,
                        'min_samples_leaf': min_samples_leaf,
                        'criterion': criterion
                    }

print("Best Accuracy: ", best_accuracy)
print("Best Hyperparameters: ", best_params)

Best Accuracy:  0.5873925501432665
Best Hyperparameters:  {'max_depth': 10, 'min_samples_split': 10, 'min_samples_leaf': 1, 'criterion': 'gini'}

In [57]:
                                          #DECISION TREE CLASSIFICATION 

from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report 

X=NT.drop(columns=["rating_category"]) 
y=NT["rating_category"]  

X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3,random_state=42) 


model_tree=DecisionTreeClassifier(max_depth=10,random_state=42) 


model_tree.fit(X_train,y_train) 

y_pred=model_tree.predict(X_test) 

print("Accuracy: ", accuracy_score(y_test, y_pred))
print("Confusion Matrix: \n", confusion_matrix(y_test, y_pred))
print("Classification Report: \n", classification_report(y_test, y_pred))

Accuracy:  0.5735575085976309
Confusion Matrix:
 [[1143   87  120]
 [ 301  156   88]
 [ 437   83  202]]
Classification Report:
               precision    recall  f1-score   support

           0       0.61      0.85      0.71      1350
           1       0.48      0.29      0.36       545
           2       0.49      0.28      0.36       722

    accuracy                           0.57      2617
   macro avg       0.53      0.47      0.47      2617
weighted avg       0.55      0.57      0.54      2617

In [59]:
                                #HYPERPARAMETER TUNING USING GRIDSEARCHCV 


from sklearn.model_selection import GridSearchCV
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

param_grid = {
    'max_depth': [5, 10, 15, 20, None],  
    'min_samples_split': [2, 5, 10],     
    'min_samples_leaf': [1, 2, 5],       
    'criterion': ['gini', 'entropy'],   
    'max_features': [None, 'sqrt', 'log2'],
    'splitter': ['best', 'random']      
}

grid_search = GridSearchCV(estimator=model_tree, param_grid=param_grid, cv=5, scoring='accuracy', n_jobs=-1, verbose=1)

grid_search.fit(X_train, y_train)

print("Best Hyperparameters: ", grid_search.best_params_)
print("Best Accuracy from GridSearchCV: ", grid_search.best_score_)

best_clf = grid_search.best_estimator_
y_pred = best_clf.predict(X_test)


print("Test Accuracy: ", accuracy_score(y_test, y_pred))
print("Confusion Matrix: \n", confusion_matrix(y_test, y_pred))
print("Classification Report: \n", classification_report(y_test, y_pred,zero_division=0))

Fitting 5 folds for each of 540 candidates, totalling 2700 fits
Best Hyperparameters:  {'criterion': 'gini', 'max_depth': 10, 'max_features': None, 'min_samples_leaf': 2, 'min_samples_split': 10, 'splitter': 'random'}
Best Accuracy from GridSearchCV:  0.5784728991286368
Test Accuracy:  0.5827283148643485
Confusion Matrix:
 [[1170   62  118]
 [ 329  131   85]
 [ 449   49  224]]
Classification Report:
               precision    recall  f1-score   support

           0       0.60      0.87      0.71      1350
           1       0.54      0.24      0.33       545
           2       0.52      0.31      0.39       722

    accuracy                           0.58      2617
   macro avg       0.56      0.47      0.48      2617
weighted avg       0.57      0.58      0.54      2617

In [ ]:
                                SVM(Support Vector Machine)

In [17]:
                              #TRIAL AND ERROR METHOD 

from sklearn import svm 
from sklearn.model_selection import train_test_split 
from sklearn.metrics import accuracy_score

X=NT.drop(columns=["rating_category"]) 
y=NT["rating_category"]  

X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42) 

kernels = ['linear', 'poly', 'rbf', 'sigmoid']
results = {} 


for kernel in kernels:
    clf=svm.SVC(kernel=kernel,random_state=42) 
    clf.fit(X_train,y_train) 
    y_pred=clf.predict(X_test) 
    accuracy = accuracy_score(y_test, y_pred) 
    results[kernel]=accuracy 
    print(f"Kernel: {kernel}, Accuracy: {accuracy * 100:.2f}%")

Kernel: linear, Accuracy: 52.15%
Kernel: poly, Accuracy: 56.73%
Kernel: rbf, Accuracy: 56.73%
Kernel: sigmoid, Accuracy: 43.67%

In [19]:
                            #SVM CLASSIFICATION 

from sklearn import svm 
from sklearn.model_selection import train_test_split 
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report 

X=NT.drop(columns=["rating_category"]) 
y=NT["rating_category"]  

X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3,random_state=42) 

model_svm=svm.SVC(kernel='rbf',random_state=42)  

model_svm.fit(X_train,y_train) 

y_pred=model_svm.predict(X_test) 

print("Test Accuracy: ", accuracy_score(y_test, y_pred))
print("Confusion Matrix: \n", confusion_matrix(y_test, y_pred))
print("Classification Report: \n", classification_report(y_test, y_pred))

Test Accuracy:  0.5578907145586549
Confusion Matrix:
 [[1263   14   73]
 [ 461   29   55]
 [ 544   10  168]]
Classification Report:
               precision    recall  f1-score   support

           0       0.56      0.94      0.70      1350
           1       0.55      0.05      0.10       545
           2       0.57      0.23      0.33       722

    accuracy                           0.56      2617
   macro avg       0.56      0.41      0.38      2617
weighted avg       0.56      0.56      0.47      2617

In [21]:
from sklearn.model_selection import RandomizedSearchCV
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
from scipy.stats import uniform, randint


param_dist = {
    'kernel': ['linear', 'rbf'], 
    'C': uniform(0.1, 2),  
    'gamma': ['scale', 0.1],  
    'degree': randint(2, 3),  
    'coef0': uniform(0, 1)  
}

random_search = RandomizedSearchCV(
    estimator=model_svm,
    param_distributions=param_dist,
    n_iter=10,  
    scoring='accuracy',
    cv=3, 
    verbose=2,
    n_jobs=-1, 
    random_state=42
)


random_search.fit(X_train, y_train)

print(f"Best hyperparameters: {random_search.best_params_}")

best_svm = random_search.best_estimator_
y_pred = best_svm.predict(X_test)

print("Test Accuracy: ", accuracy_score(y_test, y_pred))
print("Confusion Matrix: \n", confusion_matrix(y_test, y_pred))
print("Classification Report: \n", classification_report(y_test, y_pred))

Fitting 3 folds for each of 10 candidates, totalling 30 fits
Best hyperparameters: {'C': 1.516145155592091, 'coef0': 0.020584494295802447, 'degree': 2, 'gamma': 0.1, 'kernel': 'rbf'}
Test Accuracy:  0.5685899885364921
Confusion Matrix:
 [[1253   23   74]
 [ 422   63   60]
 [ 527   23  172]]
Classification Report:
               precision    recall  f1-score   support

           0       0.57      0.93      0.71      1350
           1       0.58      0.12      0.19       545
           2       0.56      0.24      0.33       722

    accuracy                           0.57      2617
   macro avg       0.57      0.43      0.41      2617
weighted avg       0.57      0.57      0.50      2617

In [ ]:
                                   RANDOM FOREST CLASSIFICATION

In [23]:
                                    #TRIAL AND ERROR METHOD


from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report 

X=NT.drop(columns=["rating_category"]) 
y=NT["rating_category"]  

X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42) 

n_estimators_values = [50, 100, 200, 300, 400]

results = {}

for n in n_estimators_values:
    print(f"Training Random Forest with n_estimators={n}...")
    
    rf_model = RandomForestClassifier(n_estimators=n, random_state=42)
    
    rf_model.fit(X_train, y_train)
    
    y_pred = rf_model.predict(X_test)
    
    accuracy = accuracy_score(y_test, y_pred)
    
    results[n] = accuracy
    
    print(f"Accuracy for n_estimators={n}: {accuracy * 100:.2f}")
    
best_n_estimators = max(results, key=results.get)
print(f"Best n_estimators value: {best_n_estimators}")

Training Random Forest with n_estimators=50...
Accuracy for n_estimators=50: 56.91
Training Random Forest with n_estimators=100...
Accuracy for n_estimators=100: 56.79
Training Random Forest with n_estimators=200...
Accuracy for n_estimators=200: 57.02
Training Random Forest with n_estimators=300...
Accuracy for n_estimators=300: 56.85
Training Random Forest with n_estimators=400...
Accuracy for n_estimators=400: 56.85
Best n_estimators value: 200

In [29]:
                                 #RANDOM FOREST CLASSIFICATION 

from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report 

X=NT.drop(columns=["rating_category"]) 
y=NT["rating_category"]  

X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3,random_state=42) 

model_rf=RandomForestClassifier(n_estimators=200,random_state=42) 

model_rf.fit(X_train,y_train)

y_pred=model_rf.predict(X_test) 

print("Accuracy Score:",accuracy_score(y_test,y_pred)) 
print("Classification report: \n",classification_report(y_test,y_pred)) 
print("Confusion Matrix: \n",confusion_matrix(y_test,y_pred))

Accuracy Score: 0.5586549484142147
Classification report:
               precision    recall  f1-score   support

           0       0.60      0.80      0.69      1350
           1       0.49      0.24      0.32       545
           2       0.46      0.35      0.40       722

    accuracy                           0.56      2617
   macro avg       0.52      0.46      0.47      2617
weighted avg       0.54      0.56      0.53      2617

Confusion Matrix:
 [[1083   80  187]
 [ 311  129  105]
 [ 417   55  250]]

In [35]:
                                    #HYPERPARAMETER TUNING 


from sklearn.model_selection import GridSearchCV
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

param_grid = {
    'max_depth': [None, 10, 20, 30],
    'min_samples_split': [2, 5, 10],
    'min_samples_leaf': [1, 2, 4],
    'max_features': ['sqrt', 'log2',None]
}


grid_search = GridSearchCV(estimator=model_rf, param_grid=param_grid, 
                           scoring='accuracy', cv=3, verbose=2, n_jobs=-1)

grid_search.fit(X_train, y_train)

print(f"Best hyperparameters: {grid_search.best_params_}")

best_rf_model = grid_search.best_estimator_

y_pred_best = best_rf_model.predict(X_test)

print(f"Final Model Test Accuracy: {accuracy_score(y_test, y_pred_best)}")
print("Confusion Matrix: \n", confusion_matrix(y_test, y_pred_best))
print("Classification Report: \n", classification_report(y_test, y_pred_best))

Fitting 3 folds for each of 108 candidates, totalling 324 fits
Best hyperparameters: {'max_depth': 10, 'max_features': 'sqrt', 'min_samples_leaf': 4, 'min_samples_split': 2}
Final Model Test Accuracy: 0.5811998471532289
Confusion Matrix:
 [[1191   45  114]
 [ 336  113   96]
 [ 458   47  217]]
Classification Report:
               precision    recall  f1-score   support

           0       0.60      0.88      0.71      1350
           1       0.55      0.21      0.30       545
           2       0.51      0.30      0.38       722

    accuracy                           0.58      2617
   macro avg       0.55      0.46      0.46      2617
weighted avg       0.56      0.58      0.54      2617

In [ ]:
                                    XGBOOST

In [23]:
!pip install xgboost

Requirement already satisfied: xgboost in c:\users\sridhar\anaconda3\lib\site-packages (2.1.4)
Requirement already satisfied: numpy in c:\users\sridhar\anaconda3\lib\site-packages (from xgboost) (1.26.4)
Requirement already satisfied: scipy in c:\users\sridhar\anaconda3\lib\site-packages (from xgboost) (1.11.4)

In [27]:
                                   #TRIAL AND ERROR METHOD

import xgboost as xgb
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

X=NT.drop(columns=["rating_category"]) 
y=NT["rating_category"]  

X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

model1 = xgb.XGBClassifier(n_estimators=100, learning_rate=0.1, max_depth=3, subsample=0.8, colsample_bytree=0.8)
model1.fit(X_train, y_train)
y_pred1 = model1.predict(X_test)
accuracy1 = accuracy_score(y_test, y_pred1)
print(f"Trial 1 Accuracy: {accuracy1}")

model2 = xgb.XGBClassifier(n_estimators=200, learning_rate=0.05, max_depth=5, subsample=0.9, colsample_bytree=0.9)
model2.fit(X_train, y_train)
y_pred2 = model2.predict(X_test)
accuracy2 = accuracy_score(y_test, y_pred2)
print(f"Trial 2 Accuracy: {accuracy2}")

model3 = xgb.XGBClassifier(n_estimators=300, learning_rate=0.01, max_depth=7, subsample=1.0, colsample_bytree=1.0)
model3.fit(X_train, y_train)
y_pred3 = model3.predict(X_test)
accuracy3 = accuracy_score(y_test, y_pred3)
print(f"Trial 3 Accuracy: {accuracy3}")

Trial 1 Accuracy: 0.5919770773638968
Trial 2 Accuracy: 0.5988538681948424
Trial 3 Accuracy: 0.594269340974212

In [29]:
                                        #XG BOOST 

import xgboost as xgb
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report 

X=NT.drop(columns=["rating_category"]) 
y=NT["rating_category"]  

X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3,random_state=42)

model_xg=xgb.XGBClassifier(n_estimators=200,learning_rate=0.05, max_depth=5, subsample=0.9, colsample_bytree=0.9) 

model_xg.fit(X_train,y_train) 

y_pred=model_xg.predict(X_test) 

print("Accuracy Score:",accuracy_score(y_test,y_pred)) 
print("Classification report: \n",classification_report(y_test,y_pred)) 
print("Confusion Matrix: \n",confusion_matrix(y_test,y_pred))

Accuracy Score: 0.5850210164310279
Classification report:
               precision    recall  f1-score   support

           0       0.61      0.86      0.72      1350
           1       0.51      0.26      0.34       545
           2       0.51      0.32      0.39       722

    accuracy                           0.59      2617
   macro avg       0.54      0.48      0.48      2617
weighted avg       0.56      0.59      0.55      2617

Confusion Matrix:
 [[1159   72  119]
 [ 297  140  108]
 [ 430   60  232]]

In [31]:
                                    #HYPERPARAMETER TUNING

import xgboost as xgb
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

param_grid = {
    'n_estimators': [100, 200, 300], 
    'learning_rate': [0.01, 0.05, 0.1],
    'max_depth': [3, 5, 7],
    'subsample': [0.7, 0.8, 0.9],
    'colsample_bytree': [0.7, 0.8, 0.9]
}

grid_search = GridSearchCV(estimator=model_xg, param_grid=param_grid, 
                           cv=3, n_jobs=-1, verbose=2)

grid_search.fit(X_train, y_train)

best_params = grid_search.best_params_

print("Best Hyperparameters from GridSearchCV:", best_params)

best_model = grid_search.best_estimator_

y_pred = best_model.predict(X_test)

print("Accuracy Score:", accuracy_score(y_test, y_pred)) 
print("Classification Report:\n", classification_report(y_test, y_pred)) 
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))

Fitting 3 folds for each of 243 candidates, totalling 729 fits
Best Hyperparameters from GridSearchCV: {'colsample_bytree': 0.9, 'learning_rate': 0.05, 'max_depth': 3, 'n_estimators': 300, 'subsample': 0.8}
Accuracy Score: 0.5873137179977073
Classification Report:
               precision    recall  f1-score   support

           0       0.61      0.87      0.72      1350
           1       0.51      0.27      0.35       545
           2       0.52      0.30      0.38       722

    accuracy                           0.59      2617
   macro avg       0.55      0.48      0.48      2617
weighted avg       0.57      0.59      0.55      2617

Confusion Matrix:
 [[1174   73  103]
 [ 303  146   96]
 [ 440   65  217]]

In [33]:

train_predictions = best_model.predict(X_train)
test_predictions = best_model.predict(X_test)


train_accuracy = accuracy_score(y_train, train_predictions)
test_accuracy = accuracy_score(y_test, test_predictions)

print(f"Training Accuracy: {train_accuracy}")
print(f"Test Accuracy: {test_accuracy}")


The difference of 0.2% is quite small, indicating that the model generalizes well to unseen data. This is a good sign that the model isnâ€™t overfitting.

Training Accuracy: 0.6019003931847968
Test Accuracy: 0.5873137179977073

In [35]:
import joblib
joblib.dump(best_model,'best_xgboost_model.pkl')

['best_xgboost_model.pkl']

In [ ]:
XGBoost appears to be the best performing model overall, considering that it has the highest accuracy and is competitive across precision, recall, and F1-score.

Random Forest and Decision Tree also perform well but lag slightly behind XGBoost in terms of accuracy and F1-score.

KNN and SVM have lower performance overall, with SVM particularly struggling in recall and F1-score.

Thus, XGBoost stands out as the best performing model for this classification task